services:
  goal_task_service:
    build:
      context: ./goal_task_service
    ports:
      - "8001:8001"
    environment:
      - USER_SERVICE_URL=http://user_service:8000
    depends_on:
      - user_service
    networks:
      - microservices-network
    restart: unless-stopped

  user_service:
    build:
      context: ./user_service
    ports:
      - "8000:8000"
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge